name: http_certificate_pinning
description: Https Certificate pinning for Flutter
version: 1.0.4
author: Diefferson Santos <diefferson.sts@gmail.com>
homepage: https://github.com/diefferson/http_certificate_pinning

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: diefferson.http_certificate_pinning
    pluginClass: HttpCertificatePinningPlugin

